# Generated by Django 4.1.2 on 2023-01-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('ref_article', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('prix', models.FloatField()),
                ('qte_stock', models.IntegerField()),
            ],
        ),
    ]
