# Generated by Django 4.1.2 on 2023-01-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new_image',
            field=models.FileField(default=None, null=True, upload_to='article'),
        ),
    ]
