# Generated by Django 4.1.2 on 2023-01-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_article_nom_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='new_image',
            field=models.ImageField(default=None, null=True, upload_to='article'),
        ),
    ]
