# Generated by Django 4.1.3 on 2023-01-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_commande_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='email',
        ),
        migrations.AddField(
            model_name='commande',
            name='prenom',
            field=models.CharField(default='', max_length=150),
        ),
    ]
